apiVersion: v1
kind: Secret
metadata:
  name: classic-farm-tcaplus
  namespace: classic-farm
type: Opaque
stringData:
  TCAPLUS_APP_ID: REPLACE_ME
  TCAPLUS_ZONE_ID: REPLACE_ME
  TCAPLUS_DIR_URL: REPLACE_ME
  TCAPLUS_SIGNATURE: REPLACE_ME
